### ISSUE TITLE
Open Applications Panic when Monitor Power is Switched Off

### ISSUE THREAD

**Issue by km4mqk** [pop-os/gnome-shell-extension-pop-cosmic#435]
Powering off attached external monitor causes open desktop applications to panic. The Desktop remains stable and applications can be restarted, but the moment the external monitor is powered off, any open applications trigger  the following errors:

Aug 28 18:28:29 pop-os cosmic-comp[20018]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:958
                                              0: <unknown>
                                              1: <unknown>
                                              2: <unknown>
                                              3: <unknown>
                                              4: <unknown>
                                              5: <unknown>
                                              6: <unknown>
                                              7: <unknown>
                                              8: <unknown>
                                              9: <unknown>
                                             10: <unknown>
                                             11: <unknown>
                                             12: <unknown>
                                             13: <unknown>
                                             14: <unknown>
                                             15: <unknown>
                                             16: <unknown>
                                             17: __libc_start_main
                                             18: <unknown>
Aug 28 18:28:29 pop-os cosmic-comp[20018]: [EGL] 0x3001 (NOT_INITIALIZED) eglDestroySync: EGL_NOT_INITIALIZED error: In eglDestroySync: EGLDisplay (0x5fed4e3ab1d0) not intiialized
Aug 28 18:28:30 pop-os cosmic-session[1450]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
Aug 28 18:28:30 pop-os cosmic-session[1450]: cosmic-comp exited with error code 101
Aug 28 18:28:32 pop-os cosmic-comp[21388]: Failed to read config 'workspaces'
Aug 28 18:28:32 pop-os cosmic-comp[21388]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Aug 28 18:28:32 pop-os cosmic-comp[21388]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 28 18:28:32 pop-os cosmic-panel[21444]: com.system76.CosmicAppletStatusArea: Acquired bus name: org.kde.StatusNotifierWatcher
Aug 28 18:28:33 pop-os cosmic-panel[21444]: com.system76.CosmicAppletBluetooth: bluetooth subscription finished. exiting...
Aug 28 18:28:33 pop-os cosmic-panel[21444]: Exited with error code 0
Aug 28 18:28:33 pop-os cosmic-panel[21444]: Exited with error code 0
Aug 29 11:11:39 pop-os cosmic-comp[21388]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:958
                                              0: <unknown>
                                              1: <unknown>
                                              2: <unknown>
                                              3: <unknown>
                                              4: <unknown>
                                              5: <unknown>
                                              6: <unknown>
                                              7: <unknown>
                                              8: <unknown>
                                              9: <unknown>
                                             10: <unknown>
                                             11: <unknown>
                                             12: <unknown>
                                             13: <unknown>
                                             14: <unknown>
                                             15: <unknown>
                                             16: <unknown>
                                             17: __libc_start_main
                                             18: <unknown>
Aug 29 11:11:39 pop-os cosmic-comp[21388]: [EGL] 0x3001 (NOT_INITIALIZED) eglDestroySync: EGL_NOT_INITIALIZED error: In eglDestroySync: EGLDisplay (0x5bdd971a0900) not intiialized
Aug 29 11:11:40 pop-os cosmic-session[1450]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
Aug 29 11:11:40 pop-os cosmic-session[1450]: cosmic-comp exited with error code 101
Aug 29 11:11:42 pop-os cosmic-comp[23430]: Failed to read config 'workspaces'
Aug 29 11:11:42 pop-os cosmic-comp[23430]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Aug 29 11:11:42 pop-os cosmic-comp[23430]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 29 11:11:43 pop-os cosmic-panel[23486]: com.system76.CosmicAppletStatusArea: Acquired bus name: org.kde.StatusNotifierWatcher
Aug 29 11:11:43 pop-os cosmic-panel[23486]: Exited with error code 0
Aug 29 11:11:43 pop-os cosmic-panel[23486]: com.system76.CosmicAppletBluetooth: bluetooth subscription finished. exiting...
Aug 29 11:11:43 pop-os cosmic-panel[23486]: Exited with error code 0

**Comment by km4mqk** [comment]
Issue still present in fresh install of "Alpha 2" release. Desktop remains intact and functional, when monitor power is restored, but any open applications panic upon COSMIC detecting "power off" signal produced by powering down external monitor(s).

**Comment by km4mqk** [comment]
Behavior is no longer occurring after most recent update on 2024.12.30, which included new nvidia driver 565.77. 

I do not know if the nvidia driver alone was the root cause of the issue, or a combination of other factors.
